### PR TITLE
feat: Update CI to latest julia, codecov, fix tests and use Artifacts instead of Pkg

### PR DESCRIPTION
**Pull request by hellemo**

### CODE REVIEW

**Comment by kdheepak** [comment]
Thanks for looking into this! 

I'm not sure why coveralls is failing, it is enabled for me:

image

**Comment by kdheepak** [comment]
Weird. I don't understand why this is failing on Windows, and don't have a Windows machine to test.

**Comment by hellemo** [comment]
There were some carriage returns ("\r") in the test data apparently, I remove those before comparing, fairly robust if not very elegant.

I also changed the dependency from `Pkg` to `Artifacts` as suggested by Mosè and require the latest julia LTS for the new version.

All tests pass locally on windows and linux for me now.

**Comment by kdheepak** [comment]
Thank you for making those changes!

**Pull request merged**
